#![deny(unsafe_op_in_unsafe_fn)]

//! Raw bindings to the CREngine C shim.
//!
//! # Safety
//! The items exposed here are generated by `bindgen` from the C shim header and mirror the C ABI
//! exactly. Callers must uphold the contracts documented in `src/shim/shim.h`, especially around
//! pointer validity, buffer lifetimes, and alignment. No automatic safety checks are injected by
//! this module.

#[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
#[allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
#[allow(dead_code, missing_docs)]
mod bindings {
    /// Raw bindings are not generated on this target; the CREngine shim is desktop-only.
    pub const CRENGINE_SHIM_UNSUPPORTED: &str = "cre-shim bindings unavailable for this target";
}

pub use bindings::*;
